#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGestion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SIMUBA")]
	public partial class lts_autogestionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertObjetos_(Objetos_ instance);
    partial void UpdateObjetos_(Objetos_ instance);
    partial void DeleteObjetos_(Objetos_ instance);
    partial void InsertProveedores(Proveedores instance);
    partial void UpdateProveedores(Proveedores instance);
    partial void DeleteProveedores(Proveedores instance);
    partial void InsertUsuariosObjetos_(UsuariosObjetos_ instance);
    partial void UpdateUsuariosObjetos_(UsuariosObjetos_ instance);
    partial void DeleteUsuariosObjetos_(UsuariosObjetos_ instance);
    partial void Insertempleados(empleados instance);
    partial void Updateempleados(empleados instance);
    partial void Deleteempleados(empleados instance);
    partial void InsertCreditos(Creditos instance);
    partial void UpdateCreditos(Creditos instance);
    partial void DeleteCreditos(Creditos instance);
    partial void InsertCreditos_Cobros(Creditos_Cobros instance);
    partial void UpdateCreditos_Cobros(Creditos_Cobros instance);
    partial void DeleteCreditos_Cobros(Creditos_Cobros instance);
    partial void InsertCreditos_Detalles(Creditos_Detalles instance);
    partial void UpdateCreditos_Detalles(Creditos_Detalles instance);
    partial void DeleteCreditos_Detalles(Creditos_Detalles instance);
    #endregion
		
		public lts_autogestionDataContext() : 
				base(global::AutoGestion.Properties.Settings.Default.SIMUBAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public lts_autogestionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_autogestionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_autogestionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_autogestionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Objetos_> Objetos_
		{
			get
			{
				return this.GetTable<Objetos_>();
			}
		}
		
		public System.Data.Linq.Table<Proveedores> Proveedores
		{
			get
			{
				return this.GetTable<Proveedores>();
			}
		}
		
		public System.Data.Linq.Table<Roles_> Roles_
		{
			get
			{
				return this.GetTable<Roles_>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios_> Usuarios_
		{
			get
			{
				return this.GetTable<Usuarios_>();
			}
		}
		
		public System.Data.Linq.Table<UsuariosObjetos_> UsuariosObjetos_
		{
			get
			{
				return this.GetTable<UsuariosObjetos_>();
			}
		}
		
		public System.Data.Linq.Table<autogestion_liquidacion> autogestion_liquidacion
		{
			get
			{
				return this.GetTable<autogestion_liquidacion>();
			}
		}
		
		public System.Data.Linq.Table<autogestion_liquidacion_detalle> autogestion_liquidacion_detalle
		{
			get
			{
				return this.GetTable<autogestion_liquidacion_detalle>();
			}
		}
		
		public System.Data.Linq.Table<empleados_bancos> empleados_bancos
		{
			get
			{
				return this.GetTable<empleados_bancos>();
			}
		}
		
		public System.Data.Linq.Table<empleados> empleados
		{
			get
			{
				return this.GetTable<empleados>();
			}
		}
		
		public System.Data.Linq.Table<Creditos> Creditos
		{
			get
			{
				return this.GetTable<Creditos>();
			}
		}
		
		public System.Data.Linq.Table<Creditos_Cobros> Creditos_Cobros
		{
			get
			{
				return this.GetTable<Creditos_Cobros>();
			}
		}
		
		public System.Data.Linq.Table<Creditos_Detalles> Creditos_Detalles
		{
			get
			{
				return this.GetTable<Creditos_Detalles>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Objetos_")]
	public partial class Objetos_ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private System.Nullable<int> _Estado;
		
		private System.Nullable<int> _RolId;
		
		private System.Nullable<int> _ModuloId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnRolIdChanging(System.Nullable<int> value);
    partial void OnRolIdChanged();
    partial void OnModuloIdChanging(System.Nullable<int> value);
    partial void OnModuloIdChanged();
    #endregion
		
		public Objetos_()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolId", DbType="Int")]
		public System.Nullable<int> RolId
		{
			get
			{
				return this._RolId;
			}
			set
			{
				if ((this._RolId != value))
				{
					this.OnRolIdChanging(value);
					this.SendPropertyChanging();
					this._RolId = value;
					this.SendPropertyChanged("RolId");
					this.OnRolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuloId", DbType="Int")]
		public System.Nullable<int> ModuloId
		{
			get
			{
				return this._ModuloId;
			}
			set
			{
				if ((this._ModuloId != value))
				{
					this.OnModuloIdChanging(value);
					this.SendPropertyChanging();
					this._ModuloId = value;
					this.SendPropertyChanged("ModuloId");
					this.OnModuloIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedores")]
	public partial class Proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _RazonSocial;
		
		private string _TelefonoFijo;
		
		private string _Celular;
		
		private string _Email;
		
		private string _Domicilio;
		
		private System.Nullable<int> _LocalidadId;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<int> _Estado;
		
		private string _CUIT;
		
		private string _Cuenta_Banco;
		
		private string _CBU;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRazonSocialChanging(string value);
    partial void OnRazonSocialChanged();
    partial void OnTelefonoFijoChanging(string value);
    partial void OnTelefonoFijoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDomicilioChanging(string value);
    partial void OnDomicilioChanged();
    partial void OnLocalidadIdChanging(System.Nullable<int> value);
    partial void OnLocalidadIdChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnCUITChanging(string value);
    partial void OnCUITChanged();
    partial void OnCuenta_BancoChanging(string value);
    partial void OnCuenta_BancoChanged();
    partial void OnCBUChanging(string value);
    partial void OnCBUChanged();
    #endregion
		
		public Proveedores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="NVarChar(100)")]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this.OnRazonSocialChanging(value);
					this.SendPropertyChanging();
					this._RazonSocial = value;
					this.SendPropertyChanged("RazonSocial");
					this.OnRazonSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoFijo", DbType="NVarChar(50)")]
		public string TelefonoFijo
		{
			get
			{
				return this._TelefonoFijo;
			}
			set
			{
				if ((this._TelefonoFijo != value))
				{
					this.OnTelefonoFijoChanging(value);
					this.SendPropertyChanging();
					this._TelefonoFijo = value;
					this.SendPropertyChanged("TelefonoFijo");
					this.OnTelefonoFijoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(50)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="NVarChar(100)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this.OnDomicilioChanging(value);
					this.SendPropertyChanging();
					this._Domicilio = value;
					this.SendPropertyChanged("Domicilio");
					this.OnDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalidadId", DbType="Int")]
		public System.Nullable<int> LocalidadId
		{
			get
			{
				return this._LocalidadId;
			}
			set
			{
				if ((this._LocalidadId != value))
				{
					this.OnLocalidadIdChanging(value);
					this.SendPropertyChanging();
					this._LocalidadId = value;
					this.SendPropertyChanged("LocalidadId");
					this.OnLocalidadIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUIT", DbType="NVarChar(15)")]
		public string CUIT
		{
			get
			{
				return this._CUIT;
			}
			set
			{
				if ((this._CUIT != value))
				{
					this.OnCUITChanging(value);
					this.SendPropertyChanging();
					this._CUIT = value;
					this.SendPropertyChanged("CUIT");
					this.OnCUITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuenta_Banco", DbType="NVarChar(50)")]
		public string Cuenta_Banco
		{
			get
			{
				return this._Cuenta_Banco;
			}
			set
			{
				if ((this._Cuenta_Banco != value))
				{
					this.OnCuenta_BancoChanging(value);
					this.SendPropertyChanging();
					this._Cuenta_Banco = value;
					this.SendPropertyChanged("Cuenta_Banco");
					this.OnCuenta_BancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBU", DbType="NVarChar(50)")]
		public string CBU
		{
			get
			{
				return this._CBU;
			}
			set
			{
				if ((this._CBU != value))
				{
					this.OnCBUChanging(value);
					this.SendPropertyChanging();
					this._CBU = value;
					this.SendPropertyChanged("CBU");
					this.OnCBUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles_")]
	public partial class Roles_
	{
		
		private int _IdRol_;
		
		private string _NombreRol_;
		
		public Roles_()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol_", DbType="Int NOT NULL")]
		public int IdRol_
		{
			get
			{
				return this._IdRol_;
			}
			set
			{
				if ((this._IdRol_ != value))
				{
					this._IdRol_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreRol_", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreRol_
		{
			get
			{
				return this._NombreRol_;
			}
			set
			{
				if ((this._NombreRol_ != value))
				{
					this._NombreRol_ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios_")]
	public partial class Usuarios_
	{
		
		private int _idUsuario_;
		
		private int _idRol_;
		
		private string _Apellido_;
		
		private string _Nombre_;
		
		private string _Domicilio_;
		
		private string _DNI_;
		
		private string _Tel1_;
		
		private string _Tel2_;
		
		private string _Usuario_;
		
		private string _Password_;
		
		private System.Nullable<int> _CobradorId_;
		
		public Usuarios_()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario_", DbType="Int NOT NULL")]
		public int idUsuario_
		{
			get
			{
				return this._idUsuario_;
			}
			set
			{
				if ((this._idUsuario_ != value))
				{
					this._idUsuario_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol_", DbType="Int NOT NULL")]
		public int idRol_
		{
			get
			{
				return this._idRol_;
			}
			set
			{
				if ((this._idRol_ != value))
				{
					this._idRol_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido_", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido_
		{
			get
			{
				return this._Apellido_;
			}
			set
			{
				if ((this._Apellido_ != value))
				{
					this._Apellido_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre_
		{
			get
			{
				return this._Nombre_;
			}
			set
			{
				if ((this._Nombre_ != value))
				{
					this._Nombre_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio_", DbType="NVarChar(100)")]
		public string Domicilio_
		{
			get
			{
				return this._Domicilio_;
			}
			set
			{
				if ((this._Domicilio_ != value))
				{
					this._Domicilio_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_", DbType="NVarChar(50)")]
		public string DNI_
		{
			get
			{
				return this._DNI_;
			}
			set
			{
				if ((this._DNI_ != value))
				{
					this._DNI_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel1_", DbType="NVarChar(15)")]
		public string Tel1_
		{
			get
			{
				return this._Tel1_;
			}
			set
			{
				if ((this._Tel1_ != value))
				{
					this._Tel1_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel2_", DbType="NVarChar(15)")]
		public string Tel2_
		{
			get
			{
				return this._Tel2_;
			}
			set
			{
				if ((this._Tel2_ != value))
				{
					this._Tel2_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario_", DbType="NVarChar(20)")]
		public string Usuario_
		{
			get
			{
				return this._Usuario_;
			}
			set
			{
				if ((this._Usuario_ != value))
				{
					this._Usuario_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Password_
		{
			get
			{
				return this._Password_;
			}
			set
			{
				if ((this._Password_ != value))
				{
					this._Password_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CobradorId_", DbType="Int")]
		public System.Nullable<int> CobradorId_
		{
			get
			{
				return this._CobradorId_;
			}
			set
			{
				if ((this._CobradorId_ != value))
				{
					this._CobradorId_ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuariosObjetos_")]
	public partial class UsuariosObjetos_ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioObjetoId;
		
		private System.Nullable<int> _UsuarioId;
		
		private System.Nullable<int> _ObjetoId;
		
		private System.Nullable<int> _Estado;
		
		private System.Nullable<int> _RolId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioObjetoIdChanging(int value);
    partial void OnUsuarioObjetoIdChanged();
    partial void OnUsuarioIdChanging(System.Nullable<int> value);
    partial void OnUsuarioIdChanged();
    partial void OnObjetoIdChanging(System.Nullable<int> value);
    partial void OnObjetoIdChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnRolIdChanging(System.Nullable<int> value);
    partial void OnRolIdChanged();
    #endregion
		
		public UsuariosObjetos_()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioObjetoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioObjetoId
		{
			get
			{
				return this._UsuarioObjetoId;
			}
			set
			{
				if ((this._UsuarioObjetoId != value))
				{
					this.OnUsuarioObjetoIdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioObjetoId = value;
					this.SendPropertyChanged("UsuarioObjetoId");
					this.OnUsuarioObjetoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int")]
		public System.Nullable<int> UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this.OnUsuarioIdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioId = value;
					this.SendPropertyChanged("UsuarioId");
					this.OnUsuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetoId", DbType="Int")]
		public System.Nullable<int> ObjetoId
		{
			get
			{
				return this._ObjetoId;
			}
			set
			{
				if ((this._ObjetoId != value))
				{
					this.OnObjetoIdChanging(value);
					this.SendPropertyChanging();
					this._ObjetoId = value;
					this.SendPropertyChanged("ObjetoId");
					this.OnObjetoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolId", DbType="Int")]
		public System.Nullable<int> RolId
		{
			get
			{
				return this._RolId;
			}
			set
			{
				if ((this._RolId != value))
				{
					this.OnRolIdChanging(value);
					this.SendPropertyChanging();
					this._RolId = value;
					this.SendPropertyChanged("RolId");
					this.OnRolIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="egestion.autogestion_liquidacion")]
	public partial class autogestion_liquidacion
	{
		
		private long _ALIQ_ID;
		
		private System.Nullable<System.DateTime> _ALIQ_FECHA_EM;
		
		private System.Nullable<long> _ALIQ_ANIO_IMPUTACION;
		
		private System.Nullable<byte> _ALIQ_MES_IMPUTACION;
		
		private System.Nullable<decimal> _ALIQ_TOTAL;
		
		private System.Nullable<byte> _ALIQ_ESTADO;
		
		private System.Nullable<long> _ALIQ_USR_ID;
		
		private System.Nullable<long> _ALIQ_EMPR_ID;
		
		private string _ALIQ_DESCRIPCION;
		
		public autogestion_liquidacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_ID", DbType="BigInt NOT NULL")]
		public long ALIQ_ID
		{
			get
			{
				return this._ALIQ_ID;
			}
			set
			{
				if ((this._ALIQ_ID != value))
				{
					this._ALIQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_FECHA_EM", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALIQ_FECHA_EM
		{
			get
			{
				return this._ALIQ_FECHA_EM;
			}
			set
			{
				if ((this._ALIQ_FECHA_EM != value))
				{
					this._ALIQ_FECHA_EM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_ANIO_IMPUTACION", DbType="BigInt")]
		public System.Nullable<long> ALIQ_ANIO_IMPUTACION
		{
			get
			{
				return this._ALIQ_ANIO_IMPUTACION;
			}
			set
			{
				if ((this._ALIQ_ANIO_IMPUTACION != value))
				{
					this._ALIQ_ANIO_IMPUTACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_MES_IMPUTACION", DbType="TinyInt")]
		public System.Nullable<byte> ALIQ_MES_IMPUTACION
		{
			get
			{
				return this._ALIQ_MES_IMPUTACION;
			}
			set
			{
				if ((this._ALIQ_MES_IMPUTACION != value))
				{
					this._ALIQ_MES_IMPUTACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_TOTAL", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> ALIQ_TOTAL
		{
			get
			{
				return this._ALIQ_TOTAL;
			}
			set
			{
				if ((this._ALIQ_TOTAL != value))
				{
					this._ALIQ_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_ESTADO", DbType="TinyInt")]
		public System.Nullable<byte> ALIQ_ESTADO
		{
			get
			{
				return this._ALIQ_ESTADO;
			}
			set
			{
				if ((this._ALIQ_ESTADO != value))
				{
					this._ALIQ_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_USR_ID", DbType="BigInt")]
		public System.Nullable<long> ALIQ_USR_ID
		{
			get
			{
				return this._ALIQ_USR_ID;
			}
			set
			{
				if ((this._ALIQ_USR_ID != value))
				{
					this._ALIQ_USR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_EMPR_ID", DbType="BigInt")]
		public System.Nullable<long> ALIQ_EMPR_ID
		{
			get
			{
				return this._ALIQ_EMPR_ID;
			}
			set
			{
				if ((this._ALIQ_EMPR_ID != value))
				{
					this._ALIQ_EMPR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQ_DESCRIPCION", DbType="NVarChar(100)")]
		public string ALIQ_DESCRIPCION
		{
			get
			{
				return this._ALIQ_DESCRIPCION;
			}
			set
			{
				if ((this._ALIQ_DESCRIPCION != value))
				{
					this._ALIQ_DESCRIPCION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="egestion.autogestion_liquidacion_detalle")]
	public partial class autogestion_liquidacion_detalle
	{
		
		private long _ALIQD_ID;
		
		private System.Nullable<long> _ALIQD_ALIQ_ID;
		
		private System.Nullable<long> _ALIQD_EMP_ID;
		
		private System.Nullable<System.DateTime> _ALIQD_FECHA_EM;
		
		private System.Nullable<byte> _ALIQD_MES_IMPUTACION;
		
		private System.Nullable<decimal> _ALIQD_IMPORTE;
		
		private System.Nullable<byte> _ALIQD_ESTADO;
		
		public autogestion_liquidacion_detalle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_ID", DbType="BigInt NOT NULL")]
		public long ALIQD_ID
		{
			get
			{
				return this._ALIQD_ID;
			}
			set
			{
				if ((this._ALIQD_ID != value))
				{
					this._ALIQD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_ALIQ_ID", DbType="BigInt")]
		public System.Nullable<long> ALIQD_ALIQ_ID
		{
			get
			{
				return this._ALIQD_ALIQ_ID;
			}
			set
			{
				if ((this._ALIQD_ALIQ_ID != value))
				{
					this._ALIQD_ALIQ_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_EMP_ID", DbType="BigInt")]
		public System.Nullable<long> ALIQD_EMP_ID
		{
			get
			{
				return this._ALIQD_EMP_ID;
			}
			set
			{
				if ((this._ALIQD_EMP_ID != value))
				{
					this._ALIQD_EMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_FECHA_EM", DbType="DateTime2")]
		public System.Nullable<System.DateTime> ALIQD_FECHA_EM
		{
			get
			{
				return this._ALIQD_FECHA_EM;
			}
			set
			{
				if ((this._ALIQD_FECHA_EM != value))
				{
					this._ALIQD_FECHA_EM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_MES_IMPUTACION", DbType="TinyInt")]
		public System.Nullable<byte> ALIQD_MES_IMPUTACION
		{
			get
			{
				return this._ALIQD_MES_IMPUTACION;
			}
			set
			{
				if ((this._ALIQD_MES_IMPUTACION != value))
				{
					this._ALIQD_MES_IMPUTACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_IMPORTE", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> ALIQD_IMPORTE
		{
			get
			{
				return this._ALIQD_IMPORTE;
			}
			set
			{
				if ((this._ALIQD_IMPORTE != value))
				{
					this._ALIQD_IMPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALIQD_ESTADO", DbType="TinyInt")]
		public System.Nullable<byte> ALIQD_ESTADO
		{
			get
			{
				return this._ALIQD_ESTADO;
			}
			set
			{
				if ((this._ALIQD_ESTADO != value))
				{
					this._ALIQD_ESTADO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="egestion.empleados_bancos")]
	public partial class empleados_bancos
	{
		
		private long _EMPB_ID;
		
		private System.Nullable<long> _EMPB_EMP_ID;
		
		private System.Nullable<long> _EMPB_BAN_ID;
		
		private string _EMPB_CUE_CODIGO;
		
		private string _EMPB_CBU;
		
		private System.Nullable<byte> _EMPB_ESTADO;
		
		private System.Nullable<long> _EMPB_SUC_CODIGO;
		
		private string _EMPB_CUE_TIPO;
		
		private System.Nullable<int> _EMPB_CUE_LIQ;
		
		public empleados_bancos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_ID", DbType="BigInt NOT NULL")]
		public long EMPB_ID
		{
			get
			{
				return this._EMPB_ID;
			}
			set
			{
				if ((this._EMPB_ID != value))
				{
					this._EMPB_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_EMP_ID", DbType="BigInt")]
		public System.Nullable<long> EMPB_EMP_ID
		{
			get
			{
				return this._EMPB_EMP_ID;
			}
			set
			{
				if ((this._EMPB_EMP_ID != value))
				{
					this._EMPB_EMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_BAN_ID", DbType="BigInt")]
		public System.Nullable<long> EMPB_BAN_ID
		{
			get
			{
				return this._EMPB_BAN_ID;
			}
			set
			{
				if ((this._EMPB_BAN_ID != value))
				{
					this._EMPB_BAN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_CUE_CODIGO", DbType="NVarChar(45)")]
		public string EMPB_CUE_CODIGO
		{
			get
			{
				return this._EMPB_CUE_CODIGO;
			}
			set
			{
				if ((this._EMPB_CUE_CODIGO != value))
				{
					this._EMPB_CUE_CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_CBU", DbType="NVarChar(45)")]
		public string EMPB_CBU
		{
			get
			{
				return this._EMPB_CBU;
			}
			set
			{
				if ((this._EMPB_CBU != value))
				{
					this._EMPB_CBU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_ESTADO", DbType="TinyInt")]
		public System.Nullable<byte> EMPB_ESTADO
		{
			get
			{
				return this._EMPB_ESTADO;
			}
			set
			{
				if ((this._EMPB_ESTADO != value))
				{
					this._EMPB_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_SUC_CODIGO", DbType="BigInt")]
		public System.Nullable<long> EMPB_SUC_CODIGO
		{
			get
			{
				return this._EMPB_SUC_CODIGO;
			}
			set
			{
				if ((this._EMPB_SUC_CODIGO != value))
				{
					this._EMPB_SUC_CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_CUE_TIPO", DbType="NVarChar(45)")]
		public string EMPB_CUE_TIPO
		{
			get
			{
				return this._EMPB_CUE_TIPO;
			}
			set
			{
				if ((this._EMPB_CUE_TIPO != value))
				{
					this._EMPB_CUE_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPB_CUE_LIQ", DbType="Int")]
		public System.Nullable<int> EMPB_CUE_LIQ
		{
			get
			{
				return this._EMPB_CUE_LIQ;
			}
			set
			{
				if ((this._EMPB_CUE_LIQ != value))
				{
					this._EMPB_CUE_LIQ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.empleados")]
	public partial class empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMP_ID;
		
		private System.Nullable<long> _EMP_CODIGO;
		
		private string _EMP_NOMBRE;
		
		private string _EMP_DNI;
		
		private string _EMP_TEL;
		
		private System.Nullable<long> _EMP_CATE_ID;
		
		private System.Nullable<long> _EMP_EMPR_ID;
		
		private System.Nullable<long> _EMP_ESTADO;
		
		private string _EMP_DIRECCION;
		
		private System.Nullable<decimal> _EMP_SUELDO;
		
		private string _EMP_APELLIDO;
		
		private System.Nullable<long> _EMP_CCO_ID;
		
		private System.Nullable<System.DateTime> _EMP_FECHA_INGRESO;
		
		private System.Nullable<int> _EMP_REGIMEN;
		
		private string _EMP_CELULAR;
		
		private System.Nullable<int> _EMP_ESTADO_CIVIL;
		
		private System.Nullable<long> _EMP_CANTIDAD_HIJOS;
		
		private System.Nullable<System.DateTime> _EMP_FECHA_BAJA;
		
		private System.Nullable<System.DateTime> _EMP_FECHA_NACIMIENTO;
		
		private System.Nullable<long> _EMP_TIPO;
		
		private System.Nullable<long> _EMP_SUC_ID;
		
		private System.Nullable<long> _EMP_TIPO_DOC;
		
		private System.Nullable<decimal> _EMP_COMISION_PORCMAY;
		
		private System.Nullable<decimal> _EMP_COMISION_PORCMIN;
		
		private System.Nullable<decimal> _EMP_COMISION_PORCCOSTO;
		
		private System.Nullable<long> _EMP_COMISION_NOCOBRA;
		
		private string _EMP_SEXO;
		
		private System.Nullable<System.DateTime> _EMP_FECHA_INICIO_ACTIVIDAD;
		
		private System.Nullable<long> _EMP_BAN_ID;
		
		private string _EMP_NRO_CUENTA;
		
		private string _EMP_CUIT;
		
		private System.Nullable<long> _EMP_PAIS_ID;
		
		private string _EMP_MAIL;
		
		private System.Nullable<byte> _EMP_USAENWEB;
		
		private string _EMP_USUARIOWEB;
		
		private string _EMP_CLAVEWEB;
		
		private string _EMP_USUARIOCEL;
		
		private string _EMP_CLAVECEL;
		
		private string _EMP_CBU;
		
		private System.Nullable<long> _EMP_PLANTEL;
		
		private System.Nullable<long> _EMP_EPROF_ID;
		
		private System.Nullable<long> _EMP_TAREA;
		
		private System.Nullable<long> _EMP_FUNCION;
		
		private string _EMP_MATRICULA;
		
		private System.Nullable<long> _EMP_CONTRATO;
		
		private System.Nullable<long> _EMP_ESP_ID;
		
		private System.Nullable<long> _EMP_ACTIVO;
		
		private System.Nullable<long> _EMP_AFECTADO_COVID;
		
		private System.Nullable<System.DateTime> _EMP_FECHA_UM;
		
		private string _EMP_CUIT_EFECTOR;
		
		private string _EMP_APENOM;
		
		private System.Nullable<int> _EMP_ESTADO_CREDITO;
		
		private System.Nullable<int> _EMP_LEGAJO;
		
		private System.Nullable<decimal> _EMP_MARGEN;
		
		private System.Nullable<decimal> _EMP_MARGEN_DISPONIBLE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMP_IDChanging(int value);
    partial void OnEMP_IDChanged();
    partial void OnEMP_CODIGOChanging(System.Nullable<long> value);
    partial void OnEMP_CODIGOChanged();
    partial void OnEMP_NOMBREChanging(string value);
    partial void OnEMP_NOMBREChanged();
    partial void OnEMP_DNIChanging(string value);
    partial void OnEMP_DNIChanged();
    partial void OnEMP_TELChanging(string value);
    partial void OnEMP_TELChanged();
    partial void OnEMP_CATE_IDChanging(System.Nullable<long> value);
    partial void OnEMP_CATE_IDChanged();
    partial void OnEMP_EMPR_IDChanging(System.Nullable<long> value);
    partial void OnEMP_EMPR_IDChanged();
    partial void OnEMP_ESTADOChanging(System.Nullable<long> value);
    partial void OnEMP_ESTADOChanged();
    partial void OnEMP_DIRECCIONChanging(string value);
    partial void OnEMP_DIRECCIONChanged();
    partial void OnEMP_SUELDOChanging(System.Nullable<decimal> value);
    partial void OnEMP_SUELDOChanged();
    partial void OnEMP_APELLIDOChanging(string value);
    partial void OnEMP_APELLIDOChanged();
    partial void OnEMP_CCO_IDChanging(System.Nullable<long> value);
    partial void OnEMP_CCO_IDChanged();
    partial void OnEMP_FECHA_INGRESOChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_FECHA_INGRESOChanged();
    partial void OnEMP_REGIMENChanging(System.Nullable<int> value);
    partial void OnEMP_REGIMENChanged();
    partial void OnEMP_CELULARChanging(string value);
    partial void OnEMP_CELULARChanged();
    partial void OnEMP_ESTADO_CIVILChanging(System.Nullable<int> value);
    partial void OnEMP_ESTADO_CIVILChanged();
    partial void OnEMP_CANTIDAD_HIJOSChanging(System.Nullable<long> value);
    partial void OnEMP_CANTIDAD_HIJOSChanged();
    partial void OnEMP_FECHA_BAJAChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_FECHA_BAJAChanged();
    partial void OnEMP_FECHA_NACIMIENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_FECHA_NACIMIENTOChanged();
    partial void OnEMP_TIPOChanging(System.Nullable<long> value);
    partial void OnEMP_TIPOChanged();
    partial void OnEMP_SUC_IDChanging(System.Nullable<long> value);
    partial void OnEMP_SUC_IDChanged();
    partial void OnEMP_TIPO_DOCChanging(System.Nullable<long> value);
    partial void OnEMP_TIPO_DOCChanged();
    partial void OnEMP_COMISION_PORCMAYChanging(System.Nullable<decimal> value);
    partial void OnEMP_COMISION_PORCMAYChanged();
    partial void OnEMP_COMISION_PORCMINChanging(System.Nullable<decimal> value);
    partial void OnEMP_COMISION_PORCMINChanged();
    partial void OnEMP_COMISION_PORCCOSTOChanging(System.Nullable<decimal> value);
    partial void OnEMP_COMISION_PORCCOSTOChanged();
    partial void OnEMP_COMISION_NOCOBRAChanging(System.Nullable<long> value);
    partial void OnEMP_COMISION_NOCOBRAChanged();
    partial void OnEMP_SEXOChanging(string value);
    partial void OnEMP_SEXOChanged();
    partial void OnEMP_FECHA_INICIO_ACTIVIDADChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_FECHA_INICIO_ACTIVIDADChanged();
    partial void OnEMP_BAN_IDChanging(System.Nullable<long> value);
    partial void OnEMP_BAN_IDChanged();
    partial void OnEMP_NRO_CUENTAChanging(string value);
    partial void OnEMP_NRO_CUENTAChanged();
    partial void OnEMP_CUITChanging(string value);
    partial void OnEMP_CUITChanged();
    partial void OnEMP_PAIS_IDChanging(System.Nullable<long> value);
    partial void OnEMP_PAIS_IDChanged();
    partial void OnEMP_MAILChanging(string value);
    partial void OnEMP_MAILChanged();
    partial void OnEMP_USAENWEBChanging(System.Nullable<byte> value);
    partial void OnEMP_USAENWEBChanged();
    partial void OnEMP_USUARIOWEBChanging(string value);
    partial void OnEMP_USUARIOWEBChanged();
    partial void OnEMP_CLAVEWEBChanging(string value);
    partial void OnEMP_CLAVEWEBChanged();
    partial void OnEMP_USUARIOCELChanging(string value);
    partial void OnEMP_USUARIOCELChanged();
    partial void OnEMP_CLAVECELChanging(string value);
    partial void OnEMP_CLAVECELChanged();
    partial void OnEMP_CBUChanging(string value);
    partial void OnEMP_CBUChanged();
    partial void OnEMP_PLANTELChanging(System.Nullable<long> value);
    partial void OnEMP_PLANTELChanged();
    partial void OnEMP_EPROF_IDChanging(System.Nullable<long> value);
    partial void OnEMP_EPROF_IDChanged();
    partial void OnEMP_TAREAChanging(System.Nullable<long> value);
    partial void OnEMP_TAREAChanged();
    partial void OnEMP_FUNCIONChanging(System.Nullable<long> value);
    partial void OnEMP_FUNCIONChanged();
    partial void OnEMP_MATRICULAChanging(string value);
    partial void OnEMP_MATRICULAChanged();
    partial void OnEMP_CONTRATOChanging(System.Nullable<long> value);
    partial void OnEMP_CONTRATOChanged();
    partial void OnEMP_ESP_IDChanging(System.Nullable<long> value);
    partial void OnEMP_ESP_IDChanged();
    partial void OnEMP_ACTIVOChanging(System.Nullable<long> value);
    partial void OnEMP_ACTIVOChanged();
    partial void OnEMP_AFECTADO_COVIDChanging(System.Nullable<long> value);
    partial void OnEMP_AFECTADO_COVIDChanged();
    partial void OnEMP_FECHA_UMChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_FECHA_UMChanged();
    partial void OnEMP_CUIT_EFECTORChanging(string value);
    partial void OnEMP_CUIT_EFECTORChanged();
    partial void OnEMP_APENOMChanging(string value);
    partial void OnEMP_APENOMChanged();
    partial void OnEMP_ESTADO_CREDITOChanging(System.Nullable<int> value);
    partial void OnEMP_ESTADO_CREDITOChanged();
    partial void OnEMP_LEGAJOChanging(System.Nullable<int> value);
    partial void OnEMP_LEGAJOChanged();
    partial void OnEMP_MARGENChanging(System.Nullable<decimal> value);
    partial void OnEMP_MARGENChanged();
    partial void OnEMP_MARGEN_DISPONIBLEChanging(System.Nullable<decimal> value);
    partial void OnEMP_MARGEN_DISPONIBLEChanged();
    #endregion
		
		public empleados()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CODIGO", DbType="BigInt")]
		public System.Nullable<long> EMP_CODIGO
		{
			get
			{
				return this._EMP_CODIGO;
			}
			set
			{
				if ((this._EMP_CODIGO != value))
				{
					this.OnEMP_CODIGOChanging(value);
					this.SendPropertyChanging();
					this._EMP_CODIGO = value;
					this.SendPropertyChanged("EMP_CODIGO");
					this.OnEMP_CODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NOMBRE", DbType="NVarChar(45)")]
		public string EMP_NOMBRE
		{
			get
			{
				return this._EMP_NOMBRE;
			}
			set
			{
				if ((this._EMP_NOMBRE != value))
				{
					this.OnEMP_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._EMP_NOMBRE = value;
					this.SendPropertyChanged("EMP_NOMBRE");
					this.OnEMP_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DNI", DbType="NVarChar(45)")]
		public string EMP_DNI
		{
			get
			{
				return this._EMP_DNI;
			}
			set
			{
				if ((this._EMP_DNI != value))
				{
					this.OnEMP_DNIChanging(value);
					this.SendPropertyChanging();
					this._EMP_DNI = value;
					this.SendPropertyChanged("EMP_DNI");
					this.OnEMP_DNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TEL", DbType="NVarChar(45)")]
		public string EMP_TEL
		{
			get
			{
				return this._EMP_TEL;
			}
			set
			{
				if ((this._EMP_TEL != value))
				{
					this.OnEMP_TELChanging(value);
					this.SendPropertyChanging();
					this._EMP_TEL = value;
					this.SendPropertyChanged("EMP_TEL");
					this.OnEMP_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CATE_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_CATE_ID
		{
			get
			{
				return this._EMP_CATE_ID;
			}
			set
			{
				if ((this._EMP_CATE_ID != value))
				{
					this.OnEMP_CATE_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_CATE_ID = value;
					this.SendPropertyChanged("EMP_CATE_ID");
					this.OnEMP_CATE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_EMPR_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_EMPR_ID
		{
			get
			{
				return this._EMP_EMPR_ID;
			}
			set
			{
				if ((this._EMP_EMPR_ID != value))
				{
					this.OnEMP_EMPR_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_EMPR_ID = value;
					this.SendPropertyChanged("EMP_EMPR_ID");
					this.OnEMP_EMPR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ESTADO", DbType="BigInt")]
		public System.Nullable<long> EMP_ESTADO
		{
			get
			{
				return this._EMP_ESTADO;
			}
			set
			{
				if ((this._EMP_ESTADO != value))
				{
					this.OnEMP_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._EMP_ESTADO = value;
					this.SendPropertyChanged("EMP_ESTADO");
					this.OnEMP_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DIRECCION", DbType="NVarChar(100)")]
		public string EMP_DIRECCION
		{
			get
			{
				return this._EMP_DIRECCION;
			}
			set
			{
				if ((this._EMP_DIRECCION != value))
				{
					this.OnEMP_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._EMP_DIRECCION = value;
					this.SendPropertyChanged("EMP_DIRECCION");
					this.OnEMP_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_SUELDO", DbType="Decimal(14,4)")]
		public System.Nullable<decimal> EMP_SUELDO
		{
			get
			{
				return this._EMP_SUELDO;
			}
			set
			{
				if ((this._EMP_SUELDO != value))
				{
					this.OnEMP_SUELDOChanging(value);
					this.SendPropertyChanging();
					this._EMP_SUELDO = value;
					this.SendPropertyChanged("EMP_SUELDO");
					this.OnEMP_SUELDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_APELLIDO", DbType="NVarChar(45)")]
		public string EMP_APELLIDO
		{
			get
			{
				return this._EMP_APELLIDO;
			}
			set
			{
				if ((this._EMP_APELLIDO != value))
				{
					this.OnEMP_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._EMP_APELLIDO = value;
					this.SendPropertyChanged("EMP_APELLIDO");
					this.OnEMP_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CCO_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_CCO_ID
		{
			get
			{
				return this._EMP_CCO_ID;
			}
			set
			{
				if ((this._EMP_CCO_ID != value))
				{
					this.OnEMP_CCO_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_CCO_ID = value;
					this.SendPropertyChanged("EMP_CCO_ID");
					this.OnEMP_CCO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FECHA_INGRESO", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EMP_FECHA_INGRESO
		{
			get
			{
				return this._EMP_FECHA_INGRESO;
			}
			set
			{
				if ((this._EMP_FECHA_INGRESO != value))
				{
					this.OnEMP_FECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._EMP_FECHA_INGRESO = value;
					this.SendPropertyChanged("EMP_FECHA_INGRESO");
					this.OnEMP_FECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_REGIMEN", DbType="Int")]
		public System.Nullable<int> EMP_REGIMEN
		{
			get
			{
				return this._EMP_REGIMEN;
			}
			set
			{
				if ((this._EMP_REGIMEN != value))
				{
					this.OnEMP_REGIMENChanging(value);
					this.SendPropertyChanging();
					this._EMP_REGIMEN = value;
					this.SendPropertyChanged("EMP_REGIMEN");
					this.OnEMP_REGIMENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CELULAR", DbType="NVarChar(45)")]
		public string EMP_CELULAR
		{
			get
			{
				return this._EMP_CELULAR;
			}
			set
			{
				if ((this._EMP_CELULAR != value))
				{
					this.OnEMP_CELULARChanging(value);
					this.SendPropertyChanging();
					this._EMP_CELULAR = value;
					this.SendPropertyChanged("EMP_CELULAR");
					this.OnEMP_CELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ESTADO_CIVIL", DbType="Int")]
		public System.Nullable<int> EMP_ESTADO_CIVIL
		{
			get
			{
				return this._EMP_ESTADO_CIVIL;
			}
			set
			{
				if ((this._EMP_ESTADO_CIVIL != value))
				{
					this.OnEMP_ESTADO_CIVILChanging(value);
					this.SendPropertyChanging();
					this._EMP_ESTADO_CIVIL = value;
					this.SendPropertyChanged("EMP_ESTADO_CIVIL");
					this.OnEMP_ESTADO_CIVILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CANTIDAD_HIJOS", DbType="BigInt")]
		public System.Nullable<long> EMP_CANTIDAD_HIJOS
		{
			get
			{
				return this._EMP_CANTIDAD_HIJOS;
			}
			set
			{
				if ((this._EMP_CANTIDAD_HIJOS != value))
				{
					this.OnEMP_CANTIDAD_HIJOSChanging(value);
					this.SendPropertyChanging();
					this._EMP_CANTIDAD_HIJOS = value;
					this.SendPropertyChanged("EMP_CANTIDAD_HIJOS");
					this.OnEMP_CANTIDAD_HIJOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FECHA_BAJA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EMP_FECHA_BAJA
		{
			get
			{
				return this._EMP_FECHA_BAJA;
			}
			set
			{
				if ((this._EMP_FECHA_BAJA != value))
				{
					this.OnEMP_FECHA_BAJAChanging(value);
					this.SendPropertyChanging();
					this._EMP_FECHA_BAJA = value;
					this.SendPropertyChanged("EMP_FECHA_BAJA");
					this.OnEMP_FECHA_BAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FECHA_NACIMIENTO", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EMP_FECHA_NACIMIENTO
		{
			get
			{
				return this._EMP_FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._EMP_FECHA_NACIMIENTO != value))
				{
					this.OnEMP_FECHA_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._EMP_FECHA_NACIMIENTO = value;
					this.SendPropertyChanged("EMP_FECHA_NACIMIENTO");
					this.OnEMP_FECHA_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TIPO", DbType="BigInt")]
		public System.Nullable<long> EMP_TIPO
		{
			get
			{
				return this._EMP_TIPO;
			}
			set
			{
				if ((this._EMP_TIPO != value))
				{
					this.OnEMP_TIPOChanging(value);
					this.SendPropertyChanging();
					this._EMP_TIPO = value;
					this.SendPropertyChanged("EMP_TIPO");
					this.OnEMP_TIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_SUC_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_SUC_ID
		{
			get
			{
				return this._EMP_SUC_ID;
			}
			set
			{
				if ((this._EMP_SUC_ID != value))
				{
					this.OnEMP_SUC_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_SUC_ID = value;
					this.SendPropertyChanged("EMP_SUC_ID");
					this.OnEMP_SUC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TIPO_DOC", DbType="BigInt")]
		public System.Nullable<long> EMP_TIPO_DOC
		{
			get
			{
				return this._EMP_TIPO_DOC;
			}
			set
			{
				if ((this._EMP_TIPO_DOC != value))
				{
					this.OnEMP_TIPO_DOCChanging(value);
					this.SendPropertyChanging();
					this._EMP_TIPO_DOC = value;
					this.SendPropertyChanged("EMP_TIPO_DOC");
					this.OnEMP_TIPO_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_COMISION_PORCMAY", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> EMP_COMISION_PORCMAY
		{
			get
			{
				return this._EMP_COMISION_PORCMAY;
			}
			set
			{
				if ((this._EMP_COMISION_PORCMAY != value))
				{
					this.OnEMP_COMISION_PORCMAYChanging(value);
					this.SendPropertyChanging();
					this._EMP_COMISION_PORCMAY = value;
					this.SendPropertyChanged("EMP_COMISION_PORCMAY");
					this.OnEMP_COMISION_PORCMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_COMISION_PORCMIN", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> EMP_COMISION_PORCMIN
		{
			get
			{
				return this._EMP_COMISION_PORCMIN;
			}
			set
			{
				if ((this._EMP_COMISION_PORCMIN != value))
				{
					this.OnEMP_COMISION_PORCMINChanging(value);
					this.SendPropertyChanging();
					this._EMP_COMISION_PORCMIN = value;
					this.SendPropertyChanged("EMP_COMISION_PORCMIN");
					this.OnEMP_COMISION_PORCMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_COMISION_PORCCOSTO", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> EMP_COMISION_PORCCOSTO
		{
			get
			{
				return this._EMP_COMISION_PORCCOSTO;
			}
			set
			{
				if ((this._EMP_COMISION_PORCCOSTO != value))
				{
					this.OnEMP_COMISION_PORCCOSTOChanging(value);
					this.SendPropertyChanging();
					this._EMP_COMISION_PORCCOSTO = value;
					this.SendPropertyChanged("EMP_COMISION_PORCCOSTO");
					this.OnEMP_COMISION_PORCCOSTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_COMISION_NOCOBRA", DbType="BigInt")]
		public System.Nullable<long> EMP_COMISION_NOCOBRA
		{
			get
			{
				return this._EMP_COMISION_NOCOBRA;
			}
			set
			{
				if ((this._EMP_COMISION_NOCOBRA != value))
				{
					this.OnEMP_COMISION_NOCOBRAChanging(value);
					this.SendPropertyChanging();
					this._EMP_COMISION_NOCOBRA = value;
					this.SendPropertyChanged("EMP_COMISION_NOCOBRA");
					this.OnEMP_COMISION_NOCOBRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_SEXO", DbType="NVarChar(1)")]
		public string EMP_SEXO
		{
			get
			{
				return this._EMP_SEXO;
			}
			set
			{
				if ((this._EMP_SEXO != value))
				{
					this.OnEMP_SEXOChanging(value);
					this.SendPropertyChanging();
					this._EMP_SEXO = value;
					this.SendPropertyChanged("EMP_SEXO");
					this.OnEMP_SEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FECHA_INICIO_ACTIVIDAD", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EMP_FECHA_INICIO_ACTIVIDAD
		{
			get
			{
				return this._EMP_FECHA_INICIO_ACTIVIDAD;
			}
			set
			{
				if ((this._EMP_FECHA_INICIO_ACTIVIDAD != value))
				{
					this.OnEMP_FECHA_INICIO_ACTIVIDADChanging(value);
					this.SendPropertyChanging();
					this._EMP_FECHA_INICIO_ACTIVIDAD = value;
					this.SendPropertyChanged("EMP_FECHA_INICIO_ACTIVIDAD");
					this.OnEMP_FECHA_INICIO_ACTIVIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_BAN_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_BAN_ID
		{
			get
			{
				return this._EMP_BAN_ID;
			}
			set
			{
				if ((this._EMP_BAN_ID != value))
				{
					this.OnEMP_BAN_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_BAN_ID = value;
					this.SendPropertyChanged("EMP_BAN_ID");
					this.OnEMP_BAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NRO_CUENTA", DbType="NVarChar(45)")]
		public string EMP_NRO_CUENTA
		{
			get
			{
				return this._EMP_NRO_CUENTA;
			}
			set
			{
				if ((this._EMP_NRO_CUENTA != value))
				{
					this.OnEMP_NRO_CUENTAChanging(value);
					this.SendPropertyChanging();
					this._EMP_NRO_CUENTA = value;
					this.SendPropertyChanged("EMP_NRO_CUENTA");
					this.OnEMP_NRO_CUENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CUIT", DbType="NVarChar(45)")]
		public string EMP_CUIT
		{
			get
			{
				return this._EMP_CUIT;
			}
			set
			{
				if ((this._EMP_CUIT != value))
				{
					this.OnEMP_CUITChanging(value);
					this.SendPropertyChanging();
					this._EMP_CUIT = value;
					this.SendPropertyChanged("EMP_CUIT");
					this.OnEMP_CUITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PAIS_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_PAIS_ID
		{
			get
			{
				return this._EMP_PAIS_ID;
			}
			set
			{
				if ((this._EMP_PAIS_ID != value))
				{
					this.OnEMP_PAIS_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_PAIS_ID = value;
					this.SendPropertyChanged("EMP_PAIS_ID");
					this.OnEMP_PAIS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_MAIL", DbType="NVarChar(100)")]
		public string EMP_MAIL
		{
			get
			{
				return this._EMP_MAIL;
			}
			set
			{
				if ((this._EMP_MAIL != value))
				{
					this.OnEMP_MAILChanging(value);
					this.SendPropertyChanging();
					this._EMP_MAIL = value;
					this.SendPropertyChanged("EMP_MAIL");
					this.OnEMP_MAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_USAENWEB", DbType="TinyInt")]
		public System.Nullable<byte> EMP_USAENWEB
		{
			get
			{
				return this._EMP_USAENWEB;
			}
			set
			{
				if ((this._EMP_USAENWEB != value))
				{
					this.OnEMP_USAENWEBChanging(value);
					this.SendPropertyChanging();
					this._EMP_USAENWEB = value;
					this.SendPropertyChanged("EMP_USAENWEB");
					this.OnEMP_USAENWEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_USUARIOWEB", DbType="NVarChar(45)")]
		public string EMP_USUARIOWEB
		{
			get
			{
				return this._EMP_USUARIOWEB;
			}
			set
			{
				if ((this._EMP_USUARIOWEB != value))
				{
					this.OnEMP_USUARIOWEBChanging(value);
					this.SendPropertyChanging();
					this._EMP_USUARIOWEB = value;
					this.SendPropertyChanged("EMP_USUARIOWEB");
					this.OnEMP_USUARIOWEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CLAVEWEB", DbType="NVarChar(45)")]
		public string EMP_CLAVEWEB
		{
			get
			{
				return this._EMP_CLAVEWEB;
			}
			set
			{
				if ((this._EMP_CLAVEWEB != value))
				{
					this.OnEMP_CLAVEWEBChanging(value);
					this.SendPropertyChanging();
					this._EMP_CLAVEWEB = value;
					this.SendPropertyChanged("EMP_CLAVEWEB");
					this.OnEMP_CLAVEWEBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_USUARIOCEL", DbType="NVarChar(45)")]
		public string EMP_USUARIOCEL
		{
			get
			{
				return this._EMP_USUARIOCEL;
			}
			set
			{
				if ((this._EMP_USUARIOCEL != value))
				{
					this.OnEMP_USUARIOCELChanging(value);
					this.SendPropertyChanging();
					this._EMP_USUARIOCEL = value;
					this.SendPropertyChanged("EMP_USUARIOCEL");
					this.OnEMP_USUARIOCELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CLAVECEL", DbType="NVarChar(45)")]
		public string EMP_CLAVECEL
		{
			get
			{
				return this._EMP_CLAVECEL;
			}
			set
			{
				if ((this._EMP_CLAVECEL != value))
				{
					this.OnEMP_CLAVECELChanging(value);
					this.SendPropertyChanging();
					this._EMP_CLAVECEL = value;
					this.SendPropertyChanged("EMP_CLAVECEL");
					this.OnEMP_CLAVECELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CBU", DbType="NVarChar(45)")]
		public string EMP_CBU
		{
			get
			{
				return this._EMP_CBU;
			}
			set
			{
				if ((this._EMP_CBU != value))
				{
					this.OnEMP_CBUChanging(value);
					this.SendPropertyChanging();
					this._EMP_CBU = value;
					this.SendPropertyChanged("EMP_CBU");
					this.OnEMP_CBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PLANTEL", DbType="BigInt")]
		public System.Nullable<long> EMP_PLANTEL
		{
			get
			{
				return this._EMP_PLANTEL;
			}
			set
			{
				if ((this._EMP_PLANTEL != value))
				{
					this.OnEMP_PLANTELChanging(value);
					this.SendPropertyChanging();
					this._EMP_PLANTEL = value;
					this.SendPropertyChanged("EMP_PLANTEL");
					this.OnEMP_PLANTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_EPROF_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_EPROF_ID
		{
			get
			{
				return this._EMP_EPROF_ID;
			}
			set
			{
				if ((this._EMP_EPROF_ID != value))
				{
					this.OnEMP_EPROF_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_EPROF_ID = value;
					this.SendPropertyChanged("EMP_EPROF_ID");
					this.OnEMP_EPROF_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TAREA", DbType="BigInt")]
		public System.Nullable<long> EMP_TAREA
		{
			get
			{
				return this._EMP_TAREA;
			}
			set
			{
				if ((this._EMP_TAREA != value))
				{
					this.OnEMP_TAREAChanging(value);
					this.SendPropertyChanging();
					this._EMP_TAREA = value;
					this.SendPropertyChanged("EMP_TAREA");
					this.OnEMP_TAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FUNCION", DbType="BigInt")]
		public System.Nullable<long> EMP_FUNCION
		{
			get
			{
				return this._EMP_FUNCION;
			}
			set
			{
				if ((this._EMP_FUNCION != value))
				{
					this.OnEMP_FUNCIONChanging(value);
					this.SendPropertyChanging();
					this._EMP_FUNCION = value;
					this.SendPropertyChanged("EMP_FUNCION");
					this.OnEMP_FUNCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_MATRICULA", DbType="NVarChar(45)")]
		public string EMP_MATRICULA
		{
			get
			{
				return this._EMP_MATRICULA;
			}
			set
			{
				if ((this._EMP_MATRICULA != value))
				{
					this.OnEMP_MATRICULAChanging(value);
					this.SendPropertyChanging();
					this._EMP_MATRICULA = value;
					this.SendPropertyChanged("EMP_MATRICULA");
					this.OnEMP_MATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CONTRATO", DbType="BigInt")]
		public System.Nullable<long> EMP_CONTRATO
		{
			get
			{
				return this._EMP_CONTRATO;
			}
			set
			{
				if ((this._EMP_CONTRATO != value))
				{
					this.OnEMP_CONTRATOChanging(value);
					this.SendPropertyChanging();
					this._EMP_CONTRATO = value;
					this.SendPropertyChanged("EMP_CONTRATO");
					this.OnEMP_CONTRATOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ESP_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_ESP_ID
		{
			get
			{
				return this._EMP_ESP_ID;
			}
			set
			{
				if ((this._EMP_ESP_ID != value))
				{
					this.OnEMP_ESP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ESP_ID = value;
					this.SendPropertyChanged("EMP_ESP_ID");
					this.OnEMP_ESP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ACTIVO", DbType="BigInt")]
		public System.Nullable<long> EMP_ACTIVO
		{
			get
			{
				return this._EMP_ACTIVO;
			}
			set
			{
				if ((this._EMP_ACTIVO != value))
				{
					this.OnEMP_ACTIVOChanging(value);
					this.SendPropertyChanging();
					this._EMP_ACTIVO = value;
					this.SendPropertyChanged("EMP_ACTIVO");
					this.OnEMP_ACTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_AFECTADO_COVID", DbType="BigInt")]
		public System.Nullable<long> EMP_AFECTADO_COVID
		{
			get
			{
				return this._EMP_AFECTADO_COVID;
			}
			set
			{
				if ((this._EMP_AFECTADO_COVID != value))
				{
					this.OnEMP_AFECTADO_COVIDChanging(value);
					this.SendPropertyChanging();
					this._EMP_AFECTADO_COVID = value;
					this.SendPropertyChanged("EMP_AFECTADO_COVID");
					this.OnEMP_AFECTADO_COVIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FECHA_UM", DbType="DateTime2")]
		public System.Nullable<System.DateTime> EMP_FECHA_UM
		{
			get
			{
				return this._EMP_FECHA_UM;
			}
			set
			{
				if ((this._EMP_FECHA_UM != value))
				{
					this.OnEMP_FECHA_UMChanging(value);
					this.SendPropertyChanging();
					this._EMP_FECHA_UM = value;
					this.SendPropertyChanged("EMP_FECHA_UM");
					this.OnEMP_FECHA_UMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CUIT_EFECTOR", DbType="NVarChar(45)")]
		public string EMP_CUIT_EFECTOR
		{
			get
			{
				return this._EMP_CUIT_EFECTOR;
			}
			set
			{
				if ((this._EMP_CUIT_EFECTOR != value))
				{
					this.OnEMP_CUIT_EFECTORChanging(value);
					this.SendPropertyChanging();
					this._EMP_CUIT_EFECTOR = value;
					this.SendPropertyChanged("EMP_CUIT_EFECTOR");
					this.OnEMP_CUIT_EFECTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_APENOM", DbType="NVarChar(100)")]
		public string EMP_APENOM
		{
			get
			{
				return this._EMP_APENOM;
			}
			set
			{
				if ((this._EMP_APENOM != value))
				{
					this.OnEMP_APENOMChanging(value);
					this.SendPropertyChanging();
					this._EMP_APENOM = value;
					this.SendPropertyChanged("EMP_APENOM");
					this.OnEMP_APENOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ESTADO_CREDITO", DbType="Int")]
		public System.Nullable<int> EMP_ESTADO_CREDITO
		{
			get
			{
				return this._EMP_ESTADO_CREDITO;
			}
			set
			{
				if ((this._EMP_ESTADO_CREDITO != value))
				{
					this.OnEMP_ESTADO_CREDITOChanging(value);
					this.SendPropertyChanging();
					this._EMP_ESTADO_CREDITO = value;
					this.SendPropertyChanged("EMP_ESTADO_CREDITO");
					this.OnEMP_ESTADO_CREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_LEGAJO", DbType="Int")]
		public System.Nullable<int> EMP_LEGAJO
		{
			get
			{
				return this._EMP_LEGAJO;
			}
			set
			{
				if ((this._EMP_LEGAJO != value))
				{
					this.OnEMP_LEGAJOChanging(value);
					this.SendPropertyChanging();
					this._EMP_LEGAJO = value;
					this.SendPropertyChanged("EMP_LEGAJO");
					this.OnEMP_LEGAJOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_MARGEN", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EMP_MARGEN
		{
			get
			{
				return this._EMP_MARGEN;
			}
			set
			{
				if ((this._EMP_MARGEN != value))
				{
					this.OnEMP_MARGENChanging(value);
					this.SendPropertyChanging();
					this._EMP_MARGEN = value;
					this.SendPropertyChanged("EMP_MARGEN");
					this.OnEMP_MARGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_MARGEN_DISPONIBLE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EMP_MARGEN_DISPONIBLE
		{
			get
			{
				return this._EMP_MARGEN_DISPONIBLE;
			}
			set
			{
				if ((this._EMP_MARGEN_DISPONIBLE != value))
				{
					this.OnEMP_MARGEN_DISPONIBLEChanging(value);
					this.SendPropertyChanging();
					this._EMP_MARGEN_DISPONIBLE = value;
					this.SendPropertyChanged("EMP_MARGEN_DISPONIBLE");
					this.OnEMP_MARGEN_DISPONIBLEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Creditos")]
	public partial class Creditos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Legajo;
		
		private System.Nullable<int> _EmpleadoId;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<int> _Numero;
		
		private System.Nullable<int> _UsuarioId;
		
		private System.Nullable<int> _ProveedorId;
		
		private System.Nullable<decimal> _Importe;
		
		private System.Nullable<int> _Cuotas;
		
		private System.Nullable<System.DateTime> _FechaCancelacion;
		
		private System.Nullable<int> _SinCargo;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLegajoChanging(System.Nullable<int> value);
    partial void OnLegajoChanged();
    partial void OnEmpleadoIdChanging(System.Nullable<int> value);
    partial void OnEmpleadoIdChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnNumeroChanging(System.Nullable<int> value);
    partial void OnNumeroChanged();
    partial void OnUsuarioIdChanging(System.Nullable<int> value);
    partial void OnUsuarioIdChanged();
    partial void OnProveedorIdChanging(System.Nullable<int> value);
    partial void OnProveedorIdChanged();
    partial void OnImporteChanging(System.Nullable<decimal> value);
    partial void OnImporteChanged();
    partial void OnCuotasChanging(System.Nullable<int> value);
    partial void OnCuotasChanged();
    partial void OnFechaCancelacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCancelacionChanged();
    partial void OnSinCargoChanging(System.Nullable<int> value);
    partial void OnSinCargoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Creditos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Legajo", DbType="Int")]
		public System.Nullable<int> Legajo
		{
			get
			{
				return this._Legajo;
			}
			set
			{
				if ((this._Legajo != value))
				{
					this.OnLegajoChanging(value);
					this.SendPropertyChanging();
					this._Legajo = value;
					this.SendPropertyChanged("Legajo");
					this.OnLegajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpleadoId", DbType="Int")]
		public System.Nullable<int> EmpleadoId
		{
			get
			{
				return this._EmpleadoId;
			}
			set
			{
				if ((this._EmpleadoId != value))
				{
					this.OnEmpleadoIdChanging(value);
					this.SendPropertyChanging();
					this._EmpleadoId = value;
					this.SendPropertyChanged("EmpleadoId");
					this.OnEmpleadoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int")]
		public System.Nullable<int> UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this.OnUsuarioIdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioId = value;
					this.SendPropertyChanged("UsuarioId");
					this.OnUsuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProveedorId", DbType="Int")]
		public System.Nullable<int> ProveedorId
		{
			get
			{
				return this._ProveedorId;
			}
			set
			{
				if ((this._ProveedorId != value))
				{
					this.OnProveedorIdChanging(value);
					this.SendPropertyChanging();
					this._ProveedorId = value;
					this.SendPropertyChanged("ProveedorId");
					this.OnProveedorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuotas", DbType="Int")]
		public System.Nullable<int> Cuotas
		{
			get
			{
				return this._Cuotas;
			}
			set
			{
				if ((this._Cuotas != value))
				{
					this.OnCuotasChanging(value);
					this.SendPropertyChanging();
					this._Cuotas = value;
					this.SendPropertyChanged("Cuotas");
					this.OnCuotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCancelacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCancelacion
		{
			get
			{
				return this._FechaCancelacion;
			}
			set
			{
				if ((this._FechaCancelacion != value))
				{
					this.OnFechaCancelacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCancelacion = value;
					this.SendPropertyChanged("FechaCancelacion");
					this.OnFechaCancelacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinCargo", DbType="Int")]
		public System.Nullable<int> SinCargo
		{
			get
			{
				return this._SinCargo;
			}
			set
			{
				if ((this._SinCargo != value))
				{
					this.OnSinCargoChanging(value);
					this.SendPropertyChanging();
					this._SinCargo = value;
					this.SendPropertyChanged("SinCargo");
					this.OnSinCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Creditos_Cobros")]
	public partial class Creditos_Cobros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CuotaId;
		
		private System.Nullable<int> _NumeroDeCredito;
		
		private System.Nullable<int> _NumeroCuota;
		
		private System.Nullable<decimal> _ImportePagado;
		
		private System.Nullable<System.DateTime> _FechaPago;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCuotaIdChanging(System.Nullable<int> value);
    partial void OnCuotaIdChanged();
    partial void OnNumeroDeCreditoChanging(System.Nullable<int> value);
    partial void OnNumeroDeCreditoChanged();
    partial void OnNumeroCuotaChanging(System.Nullable<int> value);
    partial void OnNumeroCuotaChanged();
    partial void OnImportePagadoChanging(System.Nullable<decimal> value);
    partial void OnImportePagadoChanged();
    partial void OnFechaPagoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaPagoChanged();
    #endregion
		
		public Creditos_Cobros()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuotaId", DbType="Int")]
		public System.Nullable<int> CuotaId
		{
			get
			{
				return this._CuotaId;
			}
			set
			{
				if ((this._CuotaId != value))
				{
					this.OnCuotaIdChanging(value);
					this.SendPropertyChanging();
					this._CuotaId = value;
					this.SendPropertyChanged("CuotaId");
					this.OnCuotaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDeCredito", DbType="Int")]
		public System.Nullable<int> NumeroDeCredito
		{
			get
			{
				return this._NumeroDeCredito;
			}
			set
			{
				if ((this._NumeroDeCredito != value))
				{
					this.OnNumeroDeCreditoChanging(value);
					this.SendPropertyChanging();
					this._NumeroDeCredito = value;
					this.SendPropertyChanged("NumeroDeCredito");
					this.OnNumeroDeCreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCuota", DbType="Int")]
		public System.Nullable<int> NumeroCuota
		{
			get
			{
				return this._NumeroCuota;
			}
			set
			{
				if ((this._NumeroCuota != value))
				{
					this.OnNumeroCuotaChanging(value);
					this.SendPropertyChanging();
					this._NumeroCuota = value;
					this.SendPropertyChanged("NumeroCuota");
					this.OnNumeroCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportePagado", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ImportePagado
		{
			get
			{
				return this._ImportePagado;
			}
			set
			{
				if ((this._ImportePagado != value))
				{
					this.OnImportePagadoChanging(value);
					this.SendPropertyChanging();
					this._ImportePagado = value;
					this.SendPropertyChanged("ImportePagado");
					this.OnImportePagadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaPago
		{
			get
			{
				return this._FechaPago;
			}
			set
			{
				if ((this._FechaPago != value))
				{
					this.OnFechaPagoChanging(value);
					this.SendPropertyChanging();
					this._FechaPago = value;
					this.SendPropertyChanged("FechaPago");
					this.OnFechaPagoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Creditos_Detalles")]
	public partial class Creditos_Detalles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _CreditoId;
		
		private System.Nullable<int> _Numero;
		
		private System.Nullable<int> _NroCuota;
		
		private System.Nullable<decimal> _Importe;
		
		private System.Nullable<System.DateTime> _FechaDePago;
		
		private System.Nullable<System.DateTime> _FechaDeVenc;
		
		private System.Nullable<bool> _PagoParcial;
		
		private System.Nullable<decimal> _Saldo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCreditoIdChanging(System.Nullable<int> value);
    partial void OnCreditoIdChanged();
    partial void OnNumeroChanging(System.Nullable<int> value);
    partial void OnNumeroChanged();
    partial void OnNroCuotaChanging(System.Nullable<int> value);
    partial void OnNroCuotaChanged();
    partial void OnImporteChanging(System.Nullable<decimal> value);
    partial void OnImporteChanged();
    partial void OnFechaDePagoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaDePagoChanged();
    partial void OnFechaDeVencChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaDeVencChanged();
    partial void OnPagoParcialChanging(System.Nullable<bool> value);
    partial void OnPagoParcialChanged();
    partial void OnSaldoChanging(System.Nullable<decimal> value);
    partial void OnSaldoChanged();
    #endregion
		
		public Creditos_Detalles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditoId", DbType="Int")]
		public System.Nullable<int> CreditoId
		{
			get
			{
				return this._CreditoId;
			}
			set
			{
				if ((this._CreditoId != value))
				{
					this.OnCreditoIdChanging(value);
					this.SendPropertyChanging();
					this._CreditoId = value;
					this.SendPropertyChanged("CreditoId");
					this.OnCreditoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
		public System.Nullable<int> Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroCuota", DbType="Int")]
		public System.Nullable<int> NroCuota
		{
			get
			{
				return this._NroCuota;
			}
			set
			{
				if ((this._NroCuota != value))
				{
					this.OnNroCuotaChanging(value);
					this.SendPropertyChanging();
					this._NroCuota = value;
					this.SendPropertyChanged("NroCuota");
					this.OnNroCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDePago", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDePago
		{
			get
			{
				return this._FechaDePago;
			}
			set
			{
				if ((this._FechaDePago != value))
				{
					this.OnFechaDePagoChanging(value);
					this.SendPropertyChanging();
					this._FechaDePago = value;
					this.SendPropertyChanged("FechaDePago");
					this.OnFechaDePagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeVenc", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDeVenc
		{
			get
			{
				return this._FechaDeVenc;
			}
			set
			{
				if ((this._FechaDeVenc != value))
				{
					this.OnFechaDeVencChanging(value);
					this.SendPropertyChanging();
					this._FechaDeVenc = value;
					this.SendPropertyChanged("FechaDeVenc");
					this.OnFechaDeVencChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagoParcial", DbType="Bit")]
		public System.Nullable<bool> PagoParcial
		{
			get
			{
				return this._PagoParcial;
			}
			set
			{
				if ((this._PagoParcial != value))
				{
					this.OnPagoParcialChanging(value);
					this.SendPropertyChanging();
					this._PagoParcial = value;
					this.SendPropertyChanged("PagoParcial");
					this.OnPagoParcialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
